In [1]:
import numpy as np

In [2]:
!ls

公共的	视频  未命名.ipynb  下载  桌面	       dev_ws	    miniconda3	town_ws
模板	图片  文档	    音乐  colcon_test  git_program  snap


In [7]:
I=np.identity(4)

In [5]:
o4=np.zeros([4,4])

In [8]:
R=np.random.rand(4,4)

In [14]:
np.asarray([1,2,3,4]).reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
print('0矩阵和单位矩阵',np.allclose(o4,I))
print('单位矩阵和单位矩阵',np.allclose(I,I))

0矩阵和单位矩阵 False
单位矩阵和单位矩阵 True


In [16]:
A = np.asarray([1,2,3,4]).reshape(2,2)

In [22]:
B = np.identity(2)

In [23]:
C = np.zeros([2,2])

In [24]:
A,B,C

(array([[1, 2],
        [3, 4]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[0., 0.],
        [0., 0.]]))

In [25]:
np.add(A,B)

array([[2., 2.],
       [3., 5.]])

In [26]:
np.subtract(A,B)

array([[0., 2.],
       [3., 3.]])

In [27]:
np.dot(A,B)

array([[1., 2.],
       [3., 4.]])

In [29]:
np.dot(B,A)

array([[1., 2.],
       [3., 4.]])

In [28]:
np.dot(A,C)

array([[0., 0.],
       [0., 0.]])

In [30]:
A_inv = np.linalg.inv(A)

In [31]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [32]:
np.dot(A,A_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [33]:
np.dot(A_inv,A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [34]:
A

array([[1, 2],
       [3, 4]])

In [35]:
A.T

array([[1, 3],
       [2, 4]])