In [5]:
import numpy as np
import math

In [6]:
np.asarray([1.0,1.0,1.0]).reshape(3,1)

array([[1.],
       [1.],
       [1.]])

In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **绕Z旋转**

In [8]:
def rz(theta):
    return np.asarray([math.cos(theta),-math.sin(theta),0,math.sin(theta),math.cos(theta),0,0,0,1]).reshape(3,3)

In [9]:
rz(math.pi/4)

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

### **绕X旋转**

In [10]:
def rx(theta):
    return np.asarray([1,0,0,0,math.cos(theta),-math.sin(theta),0,math.sin(theta),math.cos(theta)]).reshape(3,3)

In [13]:
R_BC = rx(math.pi)

In [15]:
P_CP = np.asarray([2,1,2])
P_BC = np.asarray([0,0,3])
P_BP = np.add(np.dot(R_BC,P_CP),P_BC)

In [16]:
P_BP

array([ 2., -1.,  1.])